using KotobaApi.Srs.Domain;
using KotobaApi.Srs.Scheduling;
using Xunit;

namespace KotobaApi.Tests;

/// <summary>
/// Numerical conformance of <see cref="Fsrs7Scheduler"/> against the FSRS-7
/// reference implementation (open-spaced-repetition/fsrs-rs, dual-trace
/// 34-parameter f32 model) at commit c137ee6e096f9217632397a8fb2bdb6f6e1b92ae.
/// Vectors were generated by running the pinned upstream code, not from this
/// implementation. Fixture documentation:
/// <c>Fixtures/fsrs7-vectors-c137ee6.md</c>.
/// Product/model invariants live in <see cref="SrsSchedulingTests"/>.
/// </summary>
public sealed class Fsrs7ConformanceTests
{
    private readonly Fsrs7Scheduler _scheduler = new();

    [Fact]
    public void DefaultParameters_MatchCurrentReferenceShape()
    {
        var parameters = Fsrs7Parameters.Default;
        Assert.Equal(34, parameters.Count);
        Assert.Equal(0.1104f, parameters[0]);
        Assert.Equal(0.3048f, parameters[33]);
    }

    [Theory]
    [InlineData(FsrsRating.Again, 0.1104, 6.1686, 0.08832, 0.000038275626)]
    [InlineData(FsrsRating.Hard, 2.2395, 5.261278, 1.7916001, 0.5974598)]
    [InlineData(FsrsRating.Good, 3.9221, 3.5307243, 3.13768, 4.7777247)]
    [InlineData(FsrsRating.Easy, 11.7841, 1.0, 9.427279, 53.869392)]
    public void FirstReview_MatchesUpstream(
        FsrsRating rating, double stability, double difficulty, double fastStability, double intervalDays)
    {
        var t0 = new DateTimeOffset(2026, 9, 22, 0, 0, 0, TimeSpan.Zero);

        var result = _scheduler.Schedule(new FsrsScheduleRequest(null, null, t0, rating));

        Assert.True(result.WasFirstReview);
        AssertState(result.State, stability, difficulty, fastStability);
        AssertInterval(intervalDays, result.IntervalDays);
    }

    [Fact]
    public void ForgettingCurve_MatchesUpstream()
    {
        var state = new Fsrs7MemoryState(12.0f, 9.6f, 5.0f);
        var actual = _scheduler.Retrievability(state, TimeSpan.FromDays(10));
        AssertRetrievability(0.91965944, actual);
    }

    [Theory]
    [InlineData(0.90f, 12.750781)]
    [InlineData(0.95f, 2.0461018)]
    public void IntervalSolver_MatchesUpstream(float retention, double intervalDays)
    {
        var state = new Fsrs7MemoryState(10.0f, 8.0f, 5.0f);

        var interval = _scheduler.IntervalAtRetention(state, retention);

        AssertInterval(intervalDays, interval);
        var achieved = _scheduler.Retrievability(state, TimeSpan.FromDays(interval));
        Assert.InRange(Math.Abs(achieved - retention), 0.0, 1e-3);
    }

    [Fact]
    public void Schedule_FiniteOutOfRangeMemoryState_IsClampedToReferenceBounds()
    {
        var t0 = new DateTimeOffset(2026, 9, 22, 0, 0, 0, TimeSpan.Zero);
        var states = new[]
        {
            (new Fsrs7MemoryState(0.0f, 0.0f, 0.0f), new Fsrs7MemoryState(0.0001f, 0.0001f, 1.0f)),
            (new Fsrs7MemoryState(40_000.0f, 40_000.0f, 11.0f), new Fsrs7MemoryState(36_500.0f, 36_500.0f, 10.0f)),
        };

        foreach (var (outOfRange, clamped) in states)
        {
            var actual = _scheduler.Schedule(new FsrsScheduleRequest(outOfRange, t0, t0.AddDays(1), FsrsRating.Good));
            var expected = _scheduler.Schedule(new FsrsScheduleRequest(clamped, t0, t0.AddDays(1), FsrsRating.Good));

            Assert.Equal(expected, actual);
        }
    }

    [Fact]
    public void IntervalAtRetention_FiniteOutOfRangeState_IsClampedToReferenceBounds()
    {
        var lowerBound = new Fsrs7MemoryState(0.0001f, 0.0001f, 1.0f);
        var upperBound = new Fsrs7MemoryState(36_500.0f, 36_500.0f, 10.0f);

        Assert.Equal(
            _scheduler.IntervalAtRetention(lowerBound, 0.90f),
            _scheduler.IntervalAtRetention(new Fsrs7MemoryState(0.0f, 0.0f, 0.0f), 0.90f));
        Assert.Equal(
            _scheduler.IntervalAtRetention(upperBound, 0.90f),
            _scheduler.IntervalAtRetention(new Fsrs7MemoryState(40_000.0f, 40_000.0f, 11.0f), 0.90f));
    }

    [Fact]
    public void Retrievability_FiniteLowMemoryState_UsesReferenceLowerBounds()
    {
        var lowerBound = new Fsrs7MemoryState(0.0001f, 0.0001f, 1.0f);
        var outOfRange = new Fsrs7MemoryState(0.0f, 0.0f, 0.0f);

        Assert.Equal(
            _scheduler.Retrievability(lowerBound, TimeSpan.FromDays(10)),
            _scheduler.Retrievability(outOfRange, TimeSpan.FromDays(10)));
    }

    [Theory]
    [InlineData(float.NaN)]
    [InlineData(float.PositiveInfinity)]
    [InlineData(float.NegativeInfinity)]
    public void StateEntryPoints_NonFiniteMemoryState_Throws(float nonFinite)
    {
        var t0 = new DateTimeOffset(2026, 9, 22, 0, 0, 0, TimeSpan.Zero);
        var state = new Fsrs7MemoryState(nonFinite, 1.0f, 5.0f);

        Assert.Throws<ArgumentOutOfRangeException>(() =>
            _scheduler.Schedule(new FsrsScheduleRequest(state, t0, t0.AddDays(1), FsrsRating.Good)));
        Assert.Throws<ArgumentOutOfRangeException>(() => _scheduler.IntervalAtRetention(state, 0.90f));
        Assert.Throws<ArgumentOutOfRangeException>(() => _scheduler.Retrievability(state, TimeSpan.FromDays(1)));
    }

    [Theory]
    [InlineData(0.0f, 0.0001f)]
    [InlineData(1.0f, 0.9999f)]
    public void ConfiguredDesiredRetention_IsClampedToReferenceBounds(float configured, float expected)
    {
        var t0 = new DateTimeOffset(2026, 9, 22, 0, 0, 0, TimeSpan.Zero);
        var scheduler = new Fsrs7Scheduler(new Fsrs7Options { DesiredRetention = configured });

        var result = scheduler.Schedule(new FsrsScheduleRequest(null, null, t0, FsrsRating.Good));

        Assert.Equal(expected, result.DesiredRetention);
    }

    [Fact]
    public void MixedSameDaySequence_MatchesUpstream()
    {
        var t0 = new DateTimeOffset(2026, 9, 22, 0, 0, 0, TimeSpan.Zero);
        Fsrs7MemoryState? state = null;
        DateTimeOffset? last = null;

        var r0 = Schedule(ref state, ref last, t0, FsrsRating.Good);
        AssertFirstReview(r0);
        AssertState(r0.State, 3.9221, 3.5307243, 3.13768);
        AssertInterval(4.7777247, r0.IntervalDays);

        var r1 = Schedule(ref state, ref last, t0.AddHours(6), FsrsRating.Good);
        AssertRetrievability(0.95115894, r1.RetrievabilityBeforeReview!.Value);
        AssertState(r1.State, 7.227843, 3.4977171, 101.86815);
        AssertInterval(14.995506, r1.IntervalDays);

        var r2At = t0.AddHours(6).AddDays(1.5);
        var r2 = Schedule(ref state, ref last, r2At, FsrsRating.Hard);
        AssertRetrievability(0.9628668, r2.RetrievabilityBeforeReview!.Value);
        AssertState(r2.State, 10.180039, 6.0976644, 218.94925);
        AssertInterval(11.329172, r2.IntervalDays);

        var r3At = r2At.AddHours(2.4);
        var r3 = Schedule(ref state, ref last, r3At, FsrsRating.Again);
        AssertRetrievability(0.9872349, r3.RetrievabilityBeforeReview!.Value);
        AssertState(r3.State, 2.310639, 9.474576, 0.4219594);
        AssertInterval(0.008041879, r3.IntervalDays);

        var r4 = Schedule(ref state, ref last, r3At.AddDays(2), FsrsRating.Easy);
        AssertRetrievability(0.776888, r4.RetrievabilityBeforeReview!.Value);
        AssertState(r4.State, 4.367909, 9.169398, 23.296722);
        AssertInterval(0.7417048, r4.IntervalDays);
    }

    [Fact]
    public void SuccessAfterLongDelay_MatchesUpstream()
    {
        var t0 = new DateTimeOffset(2026, 9, 22, 0, 0, 0, TimeSpan.Zero);
        Fsrs7MemoryState? state = null;
        DateTimeOffset? last = null;

        Schedule(ref state, ref last, t0, FsrsRating.Good);
        var late = Schedule(ref state, ref last, t0.AddDays(30), FsrsRating.Good);

        AssertRetrievability(0.8127792, late.RetrievabilityBeforeReview!.Value);
        AssertState(late.State, 17.902279, 3.4977171, 219.67287);
        AssertInterval(47.952896, late.IntervalDays);
    }

    [Fact]
    public void FromOptimized_ClipsToReferenceBounds()
    {
        var input = Fsrs7Parameters.Default.ToArray();
        input[0] = -5.0f;
        input[2] = 0.00001f;
        input[26] = 0.1f;
        input[33] = 99.0f;

        var clipped = Fsrs7Parameters.FromOptimized(input);

        Assert.Equal(0.0001f, clipped[0]);
        Assert.True(clipped[2] >= clipped[1]);
        Assert.True(clipped[26] >= clipped[25]);
        Assert.Equal(0.6f, clipped[33]);
    }

    [Theory]
    [InlineData(33)]
    [InlineData(35)]
    public void FromOptimized_WrongCount_Throws(int count)
    {
        Assert.Throws<ArgumentException>(() =>
            Fsrs7Parameters.FromOptimized(new float[count]));
    }

    [Theory]
    [InlineData(float.NaN)]
    [InlineData(float.PositiveInfinity)]
    [InlineData(float.NegativeInfinity)]
    public void FromOptimized_NonFinite_Throws(float bad)
    {
        var input = Fsrs7Parameters.Default.ToArray();
        input[10] = bad;

        Assert.Throws<ArgumentOutOfRangeException>(() =>
            Fsrs7Parameters.FromOptimized(input));
    }

    [Fact]
    public void FromOptimized_ValidVector_PassesThrough()
    {
        var input = Fsrs7Parameters.Default.ToArray();

        var parameters = Fsrs7Parameters.FromOptimized(input);

        Assert.Equal(input, parameters.ToArray());
    }

    private FsrsScheduleResult Schedule(
        ref Fsrs7MemoryState? state,
        ref DateTimeOffset? last,
        DateTimeOffset reviewedAt,
        FsrsRating rating)
    {
        var result = _scheduler.Schedule(new FsrsScheduleRequest(state, last, reviewedAt, rating));
        state = result.State;
        last = reviewedAt;
        return result;
    }

    private static void AssertFirstReview(FsrsScheduleResult result)
    {
        Assert.True(result.WasFirstReview);
        Assert.Null(result.RetrievabilityBeforeReview);
    }

    private static void AssertState(Fsrs7MemoryState actual, double stability, double difficulty, double fastStability)
    {
        AssertNear(stability, actual.Stability, relTol: 1e-5);
        AssertNear(difficulty, actual.Difficulty, absTol: 1e-6);
        AssertNear(fastStability, actual.FastStability, relTol: 1e-5);
    }

    private static void AssertInterval(double expected, float actual) =>
        AssertNear(expected, actual, relTol: 1e-5);

    private static void AssertRetrievability(double expected, float actual) =>
        AssertNear(expected, actual, absTol: 1e-6);

    private static void AssertNear(double expected, float actual, double relTol = 1e-5, double absTol = 1e-6)
    {
        var tolerance = Math.Max(absTol, relTol * Math.Max(Math.Abs(expected), Math.Abs(actual)));
        Assert.InRange(Math.Abs(expected - actual), 0.0, tolerance);
    }
}
