// <auto-generated />
using System;
using KotobaApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KotobaApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KotobaApi.Models.ComprehensionQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correct_answer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GeneratedTextId")
                        .HasColumnType("uuid")
                        .HasColumnName("generated_text_id");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("options");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_text");

                    b.HasKey("Id")
                        .HasName("pk_comprehension_questions");

                    b.HasIndex("GeneratedTextId")
                        .HasDatabaseName("ix_comprehension_questions_generated_text_id");

                    b.ToTable("comprehension_questions", (string)null);
                });

            modelBuilder.Entity("KotobaApi.Models.Deck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_decks");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_decks_user_id");

                    b.ToTable("decks", (string)null);
                });

            modelBuilder.Entity("KotobaApi.Models.GeneratedText", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GenerationRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("generation_request_id");

                    b.HasKey("Id")
                        .HasName("pk_generated_texts");

                    b.HasIndex("GenerationRequestId")
                        .IsUnique()
                        .HasDatabaseName("ix_generated_texts_generation_request_id");

                    b.ToTable("generated_texts", (string)null);
                });

            modelBuilder.Entity("KotobaApi.Models.GeneratedTextWordUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("GeneratedTextId")
                        .HasColumnType("uuid")
                        .HasColumnName("generated_text_id");

                    b.Property<int>("Occurrences")
                        .HasColumnType("integer")
                        .HasColumnName("occurrences");

                    b.Property<Guid>("WordId")
                        .HasColumnType("uuid")
                        .HasColumnName("word_id");

                    b.HasKey("Id")
                        .HasName("pk_generated_text_word_usages");

                    b.HasIndex("GeneratedTextId")
                        .HasDatabaseName("ix_generated_text_word_usages_generated_text_id");

                    b.HasIndex("WordId")
                        .HasDatabaseName("ix_generated_text_word_usages_word_id");

                    b.ToTable("generated_text_word_usages", (string)null);
                });

            modelBuilder.Entity("KotobaApi.Models.GenerationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("PromptParams")
                        .HasColumnType("jsonb")
                        .HasColumnName("prompt_params");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_generation_requests");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_generation_requests_user_id");

                    b.ToTable("generation_requests", (string)null);
                });

            modelBuilder.Entity("KotobaApi.Models.GenerationRequestWord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("GenerationRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("generation_request_id");

                    b.Property<Guid>("WordId")
                        .HasColumnType("uuid")
                        .HasColumnName("word_id");

                    b.HasKey("Id")
                        .HasName("pk_generation_request_words");

                    b.HasIndex("GenerationRequestId")
                        .HasDatabaseName("ix_generation_request_words_generation_request_id");

                    b.HasIndex("WordId")
                        .HasDatabaseName("ix_generation_request_words_word_id");

                    b.ToTable("generation_request_words", (string)null);
                });

            modelBuilder.Entity("KotobaApi.Models.PracticeAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("GeneratedTextId")
                        .HasColumnType("uuid")
                        .HasColumnName("generated_text_id");

                    b.Property<int?>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_practice_attempts");

                    b.HasIndex("GeneratedTextId")
                        .HasDatabaseName("ix_practice_attempts_generated_text_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_practice_attempts_user_id");

                    b.ToTable("practice_attempts", (string)null);
                });

            modelBuilder.Entity("KotobaApi.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("NativeLanguage")
                        .HasColumnType("text")
                        .HasColumnName("native_language");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("KotobaApi.Models.UserAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<Guid>("ComprehensionQuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("comprehension_question_id");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<Guid>("PracticeAttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("practice_attempt_id");

                    b.Property<string>("SelectedAnswer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("selected_answer");

                    b.HasKey("Id")
                        .HasName("pk_user_answers");

                    b.HasIndex("ComprehensionQuestionId")
                        .HasDatabaseName("ix_user_answers_comprehension_question_id");

                    b.HasIndex("PracticeAttemptId")
                        .HasDatabaseName("ix_user_answers_practice_attempt_id");

                    b.ToTable("user_answers", (string)null);
                });

            modelBuilder.Entity("KotobaApi.Models.Word", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AcquisitionSource")
                        .HasColumnType("text")
                        .HasColumnName("acquisition_source");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeckId")
                        .HasColumnType("uuid")
                        .HasColumnName("deck_id");

                    b.Property<string>("ExampleSentence")
                        .HasColumnType("text")
                        .HasColumnName("example_sentence");

                    b.Property<int?>("JlptLevel")
                        .HasColumnType("integer")
                        .HasColumnName("jlpt_level");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("meaning");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PartOfSpeech")
                        .HasColumnType("text")
                        .HasColumnName("part_of_speech");

                    b.Property<string>("Reading")
                        .HasColumnType("text")
                        .HasColumnName("reading");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("term");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_words");

                    b.HasIndex("DeckId")
                        .HasDatabaseName("ix_words_deck_id");

                    b.ToTable("words", (string)null);
                });

            modelBuilder.Entity("KotobaApi.Models.WordProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double>("Difficulty")
                        .HasColumnType("double precision")
                        .HasColumnName("difficulty");

                    b.Property<DateTimeOffset>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<int>("LapseCount")
                        .HasColumnType("integer")
                        .HasColumnName("lapse_count");

                    b.Property<DateTimeOffset?>("LastReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_reviewed_at");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer")
                        .HasColumnName("review_count");

                    b.Property<double>("Stability")
                        .HasColumnType("double precision")
                        .HasColumnName("stability");

                    b.Property<double>("StabilityFast")
                        .HasColumnType("double precision")
                        .HasColumnName("stability_fast");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WordId")
                        .HasColumnType("uuid")
                        .HasColumnName("word_id");

                    b.HasKey("Id")
                        .HasName("pk_word_progress");

                    b.HasIndex("WordId")
                        .HasDatabaseName("ix_word_progress_word_id");

                    b.HasIndex("UserId", "WordId")
                        .IsUnique()
                        .HasDatabaseName("ix_word_progress_user_id_word_id");

                    b.ToTable("word_progress", (string)null);
                });

            modelBuilder.Entity("KotobaApi.Models.WordReviewEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double>("DesiredRetention")
                        .HasColumnType("double precision")
                        .HasColumnName("desired_retention");

                    b.Property<double>("DifficultyAfter")
                        .HasColumnType("double precision")
                        .HasColumnName("difficulty_after");

                    b.Property<double>("DifficultyBefore")
                        .HasColumnType("double precision")
                        .HasColumnName("difficulty_before");

                    b.Property<DateTimeOffset>("DueAtAfter")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at_after");

                    b.Property<int>("ElapsedSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("elapsed_seconds");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<DateTimeOffset>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("SchedulerVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scheduler_version");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<double>("StabilityAfter")
                        .HasColumnType("double precision")
                        .HasColumnName("stability_after");

                    b.Property<double>("StabilityBefore")
                        .HasColumnType("double precision")
                        .HasColumnName("stability_before");

                    b.Property<double>("StabilityFastAfter")
                        .HasColumnType("double precision")
                        .HasColumnName("stability_fast_after");

                    b.Property<double>("StabilityFastBefore")
                        .HasColumnType("double precision")
                        .HasColumnName("stability_fast_before");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WordId")
                        .HasColumnType("uuid")
                        .HasColumnName("word_id");

                    b.HasKey("Id")
                        .HasName("pk_word_review_events");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("ix_word_review_events_event_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_word_review_events_user_id");

                    b.HasIndex("WordId")
                        .HasDatabaseName("ix_word_review_events_word_id");

                    b.ToTable("word_review_events", (string)null);
                });

            modelBuilder.Entity("KotobaApi.Models.ComprehensionQuestion", b =>
                {
                    b.HasOne("KotobaApi.Models.GeneratedText", "GeneratedText")
                        .WithMany("Questions")
                        .HasForeignKey("GeneratedTextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comprehension_questions_generated_texts_generated_text_id");

                    b.Navigation("GeneratedText");
                });

            modelBuilder.Entity("KotobaApi.Models.Deck", b =>
                {
                    b.HasOne("KotobaApi.Models.User", "User")
                        .WithMany("Decks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_decks_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KotobaApi.Models.GeneratedText", b =>
                {
                    b.HasOne("KotobaApi.Models.GenerationRequest", "GenerationRequest")
                        .WithOne("GeneratedText")
                        .HasForeignKey("KotobaApi.Models.GeneratedText", "GenerationRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_generated_texts_generation_requests_generation_request_id");

                    b.Navigation("GenerationRequest");
                });

            modelBuilder.Entity("KotobaApi.Models.GeneratedTextWordUsage", b =>
                {
                    b.HasOne("KotobaApi.Models.GeneratedText", "GeneratedText")
                        .WithMany("WordUsages")
                        .HasForeignKey("GeneratedTextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_generated_text_word_usages_generated_texts_generated_text_id");

                    b.HasOne("KotobaApi.Models.Word", "Word")
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_generated_text_word_usages_words_word_id");

                    b.Navigation("GeneratedText");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("KotobaApi.Models.GenerationRequest", b =>
                {
                    b.HasOne("KotobaApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_generation_requests_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KotobaApi.Models.GenerationRequestWord", b =>
                {
                    b.HasOne("KotobaApi.Models.GenerationRequest", "GenerationRequest")
                        .WithMany("Words")
                        .HasForeignKey("GenerationRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_generation_request_words_generation_requests_generation_req");

                    b.HasOne("KotobaApi.Models.Word", "Word")
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_generation_request_words_words_word_id");

                    b.Navigation("GenerationRequest");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("KotobaApi.Models.PracticeAttempt", b =>
                {
                    b.HasOne("KotobaApi.Models.GeneratedText", "GeneratedText")
                        .WithMany("PracticeAttempts")
                        .HasForeignKey("GeneratedTextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_practice_attempts_generated_texts_generated_text_id");

                    b.HasOne("KotobaApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_practice_attempts_users_user_id");

                    b.Navigation("GeneratedText");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KotobaApi.Models.UserAnswer", b =>
                {
                    b.HasOne("KotobaApi.Models.ComprehensionQuestion", "ComprehensionQuestion")
                        .WithMany("UserAnswers")
                        .HasForeignKey("ComprehensionQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_answers_comprehension_questions_comprehension_question");

                    b.HasOne("KotobaApi.Models.PracticeAttempt", "PracticeAttempt")
                        .WithMany("Answers")
                        .HasForeignKey("PracticeAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_answers_practice_attempts_practice_attempt_id");

                    b.Navigation("ComprehensionQuestion");

                    b.Navigation("PracticeAttempt");
                });

            modelBuilder.Entity("KotobaApi.Models.Word", b =>
                {
                    b.HasOne("KotobaApi.Models.Deck", "Deck")
                        .WithMany()
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_words_decks_deck_id");

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("KotobaApi.Models.WordProgress", b =>
                {
                    b.HasOne("KotobaApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_word_progress_users_user_id");

                    b.HasOne("KotobaApi.Models.Word", "Word")
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_word_progress_words_word_id");

                    b.Navigation("User");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("KotobaApi.Models.WordReviewEvent", b =>
                {
                    b.HasOne("KotobaApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_word_review_events_users_user_id");

                    b.HasOne("KotobaApi.Models.Word", "Word")
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_word_review_events_words_word_id");

                    b.Navigation("User");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("KotobaApi.Models.ComprehensionQuestion", b =>
                {
                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("KotobaApi.Models.GeneratedText", b =>
                {
                    b.Navigation("PracticeAttempts");

                    b.Navigation("Questions");

                    b.Navigation("WordUsages");
                });

            modelBuilder.Entity("KotobaApi.Models.GenerationRequest", b =>
                {
                    b.Navigation("GeneratedText");

                    b.Navigation("Words");
                });

            modelBuilder.Entity("KotobaApi.Models.PracticeAttempt", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("KotobaApi.Models.User", b =>
                {
                    b.Navigation("Decks");
                });
#pragma warning restore 612, 618
        }
    }
}
